version: '3.9'

services:
  vote:
    build: ./vote
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      retries: 3
    volumes:
      - ./vote:/usr/local/app
    ports:
      - "8081:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    depends_on:
      - db
    volumes:
      - ./result:/usr/local/app
    ports:
      - "8082:80"
    networks:
      - front-tier
      - back-tier

  
  worker:
    build: ./worker
    depends_on:
      - redis
    volumes:
      - ./worker:/usr/local/app
    networks:
      - back-tier
      
 
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
    networks:
      - back-tier

volumes:
  db-data:

networks:
  front-tier:
  back-tier:
